[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /app/.venv && . /app/.venv/bin/activate && pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/gunicorn main:app --bind 0.0.0.0:$PORT"





