[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "source /app/.venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"




